### ISSUE TITLE
On Mac OS, FileIO throws error on .DS_Store file

### ISSUE THREAD

**Issue by MathewReiss** [STulling/ImageReconstructor#4]
On Mac, a .DS_Store file is automatically generated sometimes for new folders. ImageReconstructor.jl tries to read this file as if it were a stencil image, and throws the following error:

`ERROR: LoadError: On worker 2: File{DataFormat{:UNKNOWN}}("/.../stencils/.DS_Store") couldn't be recognized by FileIO.`

While it isn't difficult to manually delete this file, it would be nice if the code could elegantly handle the error and continue processing, or simply ignore any files not in standard image formats.

**Comment by STulling** [comment]
It should be fixed now, please check if it works on Mac OS. I don't have that os so I can't test.

**Comment by MathewReiss** [comment]
Looks like it correctly ignores non-image files now, including a test .txt. file I threw into the folder. Thanks for the quick fix, and awesome project! Excited to see how it grows.
